### ISSUE TITLE
S3: CI Test Failures

### ISSUE THREAD

**Issue by mda84** [scp756-221/term-project-fantasticfour-1#24]
../s3/app.py:8:1: F401 'os' imported but unused
../s3/app.py:107:5: F841 local variable 'response_update' is assigned to but never used
../s3/app.py:199:5: F841 local variable 'response_update' is assigned to but never used

**Comment by AnishaMathur** [comment]
Updated CI test files. All functions of playlist service tested locally as well as on GitHub Actions.
